---
- name: Install, enable, start Nginx and index.html
  hosts: 10.118.0.3
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create index.html and add content to it
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <body>

          <h1>My Awesome Web Page!</h1>
          <p>It worked.</p>

          </body>
          </html>
